### ISSUE TITLE
Parse error for compiler version 0.13.x on v3.0.0 tag

### ISSUE THREAD

**Issue by joneshf** [slamdata/purescript-halogen-vdom#29]
Howdy. I was looking into whether the tag at `v3.0.0` could run on `0.13.x`. Looks like there's [one small thing that doesn't parse](https://github.com/slamdata/purescript-halogen-vdom/compare/v3.0.0...joneshf:fix-parse-error-for-0.13.x). It should be a non-breaking change as it parses with both `0.12.x` and `0.13.x` (unless I'm forgetting something). Would you be willing to accept a PR for the change and push out a `v3.0.1`? If so, it looks like a branch has to be made starting at `v3.0.0`, then I should be able to make a PR. If not, no big.

**Comment by natefaubion** [comment]
Yes, that would be great. I'm not sure how this didn't get caught leading up to 0.13.

**Comment by joneshf** [comment]
Great! Lemme know when a branch is made so I can submit a PR.

`v3.0.0` is over a year old. The line was removed [some time ago](https://github.com/slamdata/purescript-halogen-vdom/commit/6470c51d86c880c786bf821c28471e4efe865642#diff-17229d73fa44e26f7863806cab70bd8dL100). Newer versions are compatible with compiler version `0.13.x`. We ran into this because we're still on `purescript-halogen` `v4.0.0` and it depends on `v3.0.0` of this package.

Specifically, it depends on [`ElemSpec`](https://github.com/slamdata/purescript-halogen/blob/23225596473898744a6cb84fde2791aa6fe8a66a/src/Halogen/HTML/Core.purs#L74), so newer versions of this package would require changes to `purescript-halogen` based on the `v4.0.0` tag. That seems more intrusive, though it would mean the updates from `v4.0.0` on of this package would make its way into `v4.x.x` series of `purescript-halogen`.

**Comment by garyb** [comment]
Sorry, I only just realised you'd asked for a branch to be made for this. It's there now! https://github.com/slamdata/purescript-halogen-vdom/tree/v3-backport

**Comment by joneshf** [comment]
No worries. Thanks for the branch!

**Comment by garyb** [comment]
Released as v3.0.1. I've left the branch there, so if this doesn't do the trick we can always make further releases based on it 😉.

**Comment by joneshf** [comment]
Thanks!
